=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/lcd-struct.dtd
<!ELEMENT struct (struct|field|array)+>
<!ELEMENT field (#PCDATA)>
<!ELEMENT array (struct|field|array)>
<!ATTLIST struct name CDATA #REQUIRED>
<!ATTLIST struct encoding CDATA #IMPLIED>
<!ATTLIST struct multiplicity CDATA '1'>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field encoding CDATA #IMPLIED>
<!ATTLIST field multiplicity CDATA '1'>
<!ATTLIST field size CDATA '0'>
<!ATTLIST array name CDATA #REQUIRED>
<!ATTLIST array encoding CDATA #IMPLIED>
<!ATTLIST array multiplicity CDATA '1'>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apinqshto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPINQSHT</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="sht_id" size="&SHT_ID_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="slot_no" size="&SLOT_NO_LEN;"/>
    <field name="sht_stat" size="&SHT_STAT_LEN;"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="x_axis_cnt" size="&PNL_CNT_LEN;"/>
    <field name="y_axis_cnt" size="&PNL_CNT_LEN;"/>
    <field name="pnl_sht_cnt" size="&PNL_SHT_CNT_LEN;"/>
    <field name="pnl_grade" size="&MAX_SHT_PNL_CNT;"/>
    <field name="reproc_flg" size="1"/>
    <field name="route_id" size="&ROUTE_ID_LEN;"/>
    <field name="route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="ope_no" size="&OPE_NO_LEN;"/>
    <field name="ope_id" size="&OPE_ID_LEN;"/>
    <field name="ope_ver" size="&OPE_VER_LEN;"/>
    <field name="proc_id" size="&PROC_ID_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_port_id" size="&PORT_ID_LEN;"/>
    <field name="pep_lvl" size="&PEP_LVL_LEN;"/>
    <field name="recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="ds_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="ac_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="mproc_id" size="&CODE_LEN;"/>
    <field name="mproc_flg" size="1"/>
    <field name="abnd_flg" size="1"/>
    <field name="deldays" size="&DELAYDAY_LEN;"/>
    <field name="sht_note_flg" size="1"/>
    <field name="fab_id" size="&FAB_ID_LEN;"/>
    <field name="line_id" size="&LINE_ID_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="charge_code" size="&CHARGE_CODE_LEN;"/>
    <field name="owner_id" size="&OWNER_ID_LEN;"/>
    <field name="prty" size="&CODE_LEN;"/>
    <field name="rwk_cnt" size="&RWK_CNT_LEN;"/>
    <field name="sales_order" size="&SALES_ORDER_LEN;"/>
    <field name="project_cd" size="&PROJECT_CD_LEN;"/>
    <field name="eng_name" size="&USER_DSC_LEN;"/>
    <field name="exp_no" size="&EXPER_NO_LEN;"/>
    <field name="dest_shop" size="&CODE_LEN;"/>
    <field name="worder_id" size="&WORDER_ID_LEN;"/>
    <field name="unit" size="&CODE_LEN;"/>
  	<field name="qrs_cnt" size="&SHT_QRS_CNT_LEN;"/>
  <struct name="oary1" multiplicity="&MAX_SHT_QRS_CNT;">
    <field name="qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="qrs_typ" size="1"/>
    <field name="qrs_date" size="&DATE_LEN;"/>
    <field name="qrs_time" size="&TIME_LEN;"/>
    <field name="qrk_date" size="&DATE_LEN;"/>
    <field name="qrk_time" size="&TIME_LEN;"/>
  </struct>
  <field name="abn_cnt" size="&SHT_ABN_CNT_LEN;"/>
  <struct name="oary2" multiplicity="&MAX_SHT_ABN_CNT;">
    <field name="seq_no" size="&SEQ_NO_LEN;"/>
    <field name="abnormal_flg" size="&ABNORMAL_FLG_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apleqalmo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPLEQALM</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
  <field name="alrt_cnt" size="2"/>
  <struct name="oary" multiplicity="300">
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="rpt_date" size="&DATE_LEN;"/>
    <field name="rpt_time" size="&TIME_LEN;"/>
    <field name="rpt_source" size="&RPT_SOURCE_LEN;"/>
    <field name="alrt_code" size="&CODE_LEN;"/>
    <field name="alrt_lvl" size="1"/>
    <field name="alert_on_off_flg" size="1"/>
    <field name="alrt_dsc" size="&ALRT_DSC_LEN;"/>
    <field name="cfm_user_id" size="&USER_ID_LEN;"/>
    <field name="cfm_date" size="&DATE_LEN;"/>
    <field name="cfm_time" size="&TIME_LEN;"/>
    <field name="alrt_id" size="&ALRT_ID_LEN;"/>
    <field name="alrt_comment" size="&COMMENT_LEN;"/>
    <field name="cfm_comment" size="&COMMENT_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/aplstbayo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPLSTBAY</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
  <field name="bay_cnt" size="3"/>
  <struct name="oary" multiplicity="100">
    <field name="bay_id" size="&BAY_ID_LEN;"/>
    <field name="bay_dsc" size="&BAY_DSC_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apinqeqpo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPINQEQP</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_dsc" size="&EQPT_DSC_LEN;"/>
    <field name="unit_typ" size="1"/>
    <field name="root_eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="prt_eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_typ" size="1"/>
    <field name="eqpt_subtyp" size="1"/>
    <field name="eqpt_cate" size="1"/>
    <field name="kanban" size="&KANBAN_SIZE;"/>
    <field name="bay_id" size="&BAY_ID_LEN;"/>
    <field name="bcs_node" size="&BCS_NODE_LEN;"/>
    <field name="tcs_node" size="&TCS_NODE_LEN;"/>
    <field name="max_sht_cnt" size="&SHT_CNT_SIZE;"/>
    <field name="max_sht_time" size="&SHT_TIME_SIZE;"/>
    <field name="floor_code" size="&FLOOR_CODE_LEN;"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_sub_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
    <field name="tcs_on_off" size="&ON_OFF_LEN;"/>
    <field name="agv_mode" size="1"/>
    <field name="cr_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="rsv_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="grp_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="pv_eqpt_sub_stat" size="&EQPT_STAT_LEN;"/>
    <field name="shtng_date" size="&DATE_LEN;"/>
    <field name="shtng_time" size="&TIME_LEN;"/>
    <field name="shtng_user" size="&USER_ID_LEN;"/>
    <field name="pr_sht_cnt" size="&SHT_CNT_SIZE;"/>
    <field name="max_over_cflg" size="1"/>
    <field name="pr_sht_time" size="&SHT_TIME_SIZE;"/>
    <field name="max_over_tflg" size="1"/>
    <field name="rst_sht_date" size="&DATE_TIME_LEN;"/>
    <field name="rst_user_id" size="&USER_ID_LEN;"/>
    <field name="alrt_flg" size="1"/>
    <field name="mtrl_chg_alrt_flg" size="1"/>
    <field name="clm_user" size="&USER_ID_LEN;"/>
    <field name="clm_date" size="&DATE_LEN;"/>
    <field name="clm_time" size="&TIME_LEN;"/>
    <field name="clm_mfsh" size="&MFGSHOP_LEN;"/>
    <field name="mon_start_flg" size="1"/>
    <field name="mon_interval" size="&MON_INTERVAL_LEN;"/>
    <field name="reticle_chk_flg" size="&RETICLE_CHK_LEN;"/>
    <field name="mtrl_chg_alrt_lvl" size="1"/>
    <field name="reticle_set_id" size="&RETICLE_SET_LEN;"/>
    <field name="xfer_triger" size="1"/>
    <field name="tcs_crr_assign" size="1"/>
    <field name="ld_crr_asgn_mode" size="1"/>
    <field name="ul_crr_asgn_mode" size="1"/>
    <field name="ld_agv_mode" size="1"/>
    <field name="ul_agv_mode" size="1"/>
    <field name="rsv_lot_cnt" size="&RSV_LOT_LEN;"/>
    <field name="max_rsv_lot_cnt" size="&RSV_LOT_LEN;"/>
    <field name="disp_prty_sel" size="1"/>
    <field name="ignore_limitation" size="1"/>
    <field name="eqpt_to_eqpt" size="1"/>
    <field name="reticle_chk" size="1"/>
    <field name="force_ret_ld" size="1"/>
    <field name="force_ret_ul" size="1"/>
    <field name="r_time_l" size="&R_TIME_LEN;"/>
    <field name="r_time_u" size="&R_TIME_LEN;"/>
    <field name="s_time_l" size="&S_TIME_LEN;"/>
    <field name="s_time_u" size="&S_TIME_LEN;"/>
    <field name="p_time_l" size="&P_TIME_LEN;"/>
    <field name="p_time_u" size="&P_TIME_LEN;"/>
    <field name="stb_lot_type" size="1"/>
    <field name="buff_flag" size="1"/>
    <field name="buff_id" size="&EQPT_ID_LEN;"/>
    <field name="min_wait_time" size="&MIN_WAIT_TIME_LEN;"/>
    <field name="comment" size="&COMMENT_LEN;"/>
    <field name="vcr_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_run_mode" size="&CODE_LEN;"/>
    <field name="eqpt_trns_cate" size="&EQPT_TRNS_CATE_LEN;"/>
    <field name="area_code" size="&CODE_LEN;"/>
    <field name="unit_mode" size="&CODE_LEN;"/>
    <field name="max_pull_cnt" size="&MAX_PULL_CNT_LEN;"/>
    <field name="real_product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="port_cnt" size="&EQPT_PT_CNT_LEN;"/>
  <struct name="oary" multiplicity="&MAX_EQPT_PT_CNT;">
    <field name="port_id" size="&PORT_ID_LEN;"/>
    <field name="port_typ" size="1"/>
    <field name="port_stat" size="&PORT_STAT_LEN;"/>
    <field name="port_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="port_date" size="&DATE_LEN;"/>
    <field name="port_time" size="&TIME_LEN;"/>
    <field name="agv_mode" size="1"/>
    <field name="sup_stocker_id" size="&EQPT_ID_LEN;"/>
    <field name="ret_stocker_id" size="&EQPT_ID_LEN;"/>
    <field name="xfer_id" size="&TCS_NODE_LEN;"/>
    <field name="xfer_node" size="&TCS_NODE_LEN;"/>
    <field name="allow_stock_out" size="1"/>
    <field name="force_empty_crr" size="1"/>
    <field name="pi_lot_sel_typ" size="1"/>
    <field name="xfer_fail" size="1"/>
    <field name="xfer_fail_to_sup" size="1"/>
    <field name="map_flg" size="1"/>
    <field name="port_mask" size="&PORT_MASK_LEN;"/>
  </struct>
  <field name="batch_cnt" size="&MAX_EQPT_BT_CNT;"/>
  <struct name="oary2" multiplicity="&MAX_EQPT_BT_CNT;">
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="crr_cnt" size="&CRR_CNT_LEN;"/>
  </struct>
  
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/aplwipeqo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPLWIPEQ</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="bay_id" size="&BAY_ID_LEN;"/>
    <field name="bay_dsc" size="&BAY_DSC_LEN;"/>
  <field name="eqpt_cnt" size="4"/>
  <struct name="oary" multiplicity="1000">
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_dsc" size="&EQPT_DSC_LEN;"/>
    <field name="eqpt_subtyp" size="1"/>
    <field name="eqpt_cate" size="1"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_sub_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
    <field name="eqpt_run_mode" size="&EQPT_MODE_LEN;"/>
    <field name="cr_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="wait_crr_cnt" size="&WIP_CRR_CNT;"/>
    <field name="inpr_crr_cnt" size="&WIP_CRR_CNT;"/>
    <field name="hld_crr_cnt" size="&WIP_CRR_CNT;"/>
    <field name="abnd_cnt" size="&WIP_SHT_CNT;"/>
    <field name="ld_crr_asgn_mode" size="1"/>
    <field name="ul_crr_asgn_mode" size="1"/>
    <field name="ld_agv_mode" size="1"/>
    <field name="ul_agv_mode" size="1"/>
    <field name="floor_code" size="&FLOOR_CODE_LEN;"/>
    <field name="mtrl_assign_mode" size="1"/>
    <field name="r_time_l" size="&R_TIME_LEN;"/>
    <field name="r_time_u" size="&R_TIME_LEN;"/>
    <field name="s_time_l" size="&S_TIME_LEN;"/>
    <field name="s_time_u" size="&S_TIME_LEN;"/>
    <field name="force_ret_ld" size="1"/>
    <field name="force_ret_ul" size="1"/>
    <field name="area_code" size="&CODE_LEN;"/>
    <field name="unit_mode" size="&CODE_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apiqcrrdi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPIQCRRD</field>
    <field name="type_id" size="&TRX_TYP_LEN;">I</field>
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="inpr_sht_flg" size="1"/>
    <field name="logon_eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="logon_date" size="&DATE_LEN;"/>
    <field name="logon_time" size="&TIME_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_port_id" size="&PORT_ID_LEN;"/>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apinqstco.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % alglen SYSTEM "alglen.dtd"> %alglen;
]>
<struct name="transaction">
  <field name="trx_id" size="&TRX_ID_LEN;"/>
  <field name="type_id" size="&TRX_TYP_LEN;"/>
  <field name="rtn_code" size="&RTN_CODE_LEN;"/>
  <field name="stocker_id" size="&EQPT_ID_LEN;"/>
  <field name="bay_id" size="&BAY_ID_LEN;"/>
  <field name="bcs_node" size="&BCS_NODE_LEN;"/>
  <field name="xfer_node" size="&BCS_NODE_LEN;"/>
  <field name="stocker_dsc" size="&EQPT_DSC_LEN;"/>
  <field name="total_shelf_cnt" size="&ZONE_T_CNT_LEN;"/>
  <field name="threshold" size="&ZONE_CNT_LEN;"/>
  <field name="eqpt_subtyp" size="1"/>
  <field name="bcs_node2" size="&BCS_NODE_LEN;"/>
  <field name="floor_code" size="&FLOOR_CODE_LEN;"/>
  <field name="zone_cnt" size="2"/>
  <struct name="oary1" multiplicity="20">
    <field name="zone_id" size="&ZONE_ID_LEN;"/>
    <field name="zone_dsc" size="&ZONE_DSC_LEN;"/>
    <field name="zone_typ" size="&ZONE_TYP_LEN;"/>
    <field name="zone_set_cnt" size="&ZONE_CNT_LEN;"/>
  </struct>
  <field name="port_cnt" size="2"/>
  <struct name="oary2" multiplicity="30">
    <field name="port_id" size="&PORT_ID_LEN;"/>
    <field name="port_usage" size="1"/>
    <field name="port_stat" size="&PORT_STAT_LEN;"/>
    <field name="xfer_id" size="&TCS_NODE_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apieqphso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPIEQPHS</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="eqp_not_cnt" size="3"/>
  <struct name="oary1" multiplicity="100">
    <field name="clm_date" size="&DATE_LEN;"/>
    <field name="clm_time" size="&TIME_LEN;"/>
    <field name="user_id" size="&USER_ID_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_sub_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="comment" size="&COMMENT_LEN;"/>
  </struct>
</struct>
