=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/lcd-struct.dtd
<!ELEMENT struct (struct|field|array)+>
<!ELEMENT field (#PCDATA)>
<!ELEMENT array (struct|field|array)>
<!ATTLIST struct name CDATA #REQUIRED>
<!ATTLIST struct encoding CDATA #IMPLIED>
<!ATTLIST struct multiplicity CDATA '1'>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field encoding CDATA #IMPLIED>
<!ATTLIST field multiplicity CDATA '1'>
<!ATTLIST field size CDATA '0'>
<!ATTLIST array name CDATA #REQUIRED>
<!ATTLIST array encoding CDATA #IMPLIED>
<!ATTLIST array multiplicity CDATA '1'>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apiopshto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
 <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPIOPSHT</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="sht_id" size="&SHT_ID_LEN;"/>
  <field name="ope_cnt" size="4"/>
  <struct name="oary" multiplicity="1000">
    <field name="clm_cate" size="&CODE_CATE_LEN;"/>
    <field name="clm_user" size="&USER_ID_LEN;"/>
    <field name="clm_date" size="&DATE_LEN;"/>
    <field name="clm_time" size="&TIME_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="slot_no" size="&SLOT_NO_LEN;"/>
    <field name="ppbox_id" size="&PPBOX_ID_LEN;"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="route_id" size="&ROUTE_ID_LEN;"/>
    <field name="route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="ope_no" size="&OPE_NO_LEN;"/>
    <field name="ope_id" size="&OPE_ID_LEN;"/>
    <field name="ope_ver" size="&OPE_VER_LEN;"/>
    <field name="proc_id" size="&PROC_ID_LEN;"/>
    <field name="eqptg_id" size="&EQPTG_ID_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_port_id" size="&PORT_ID_LEN;"/>
    <field name="pep_lvl" size="&PEP_LVL_LEN;"/>
    <field name="evt_cate" size="&CODE_CATE_LEN;"/>
    <field name="evt_code" size="&CODE_LEN;"/>
    <field name="evt_user" size="&USER_ID_LEN;"/>
    <field name="evt_date" size="&DATE_LEN;"/>
    <field name="evt_time" size="&TIME_LEN;"/>
    <field name="evt_mfdt" size="&DATE_LEN;"/>
    <field name="evt_mfwk" size="&MFGWEEK_LEN;"/>
    <field name="evt_mfmn" size="&MFGMONTH_LEN;"/>
    <field name="evt_mfsh" size="&MFGSHOP_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="product_cate" size="&CODE_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="prty" size="&CODE_LEN;"/>
    <field name="ds_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="ac_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="rep_cate" size="&REPORT_TRX_CATE;"/>
    <field name="dept_code" size="&DEPT_CODE_LEN;"/>
    <field name="rpt_user" size="&USER_ID_LEN;"/>
    <field name="sht_ope_msg" size="&SHT_OPE_MSG_LEN;"/>
    <field name="owner_id" size="&OWNER_ID_LEN;"/>
    <field name="sht_stat" size="&SHT_STAT_LEN;"/>
    <field name="nx_eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="reproc_flg" size="1"/>
    <field name="unit" size="&CODE_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apiwipeqo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPIWIPEQ</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_dsc" size="&EQPT_DSC_LEN;"/>
    <field name="eqpt_cate" size="1"/>
    <field name="recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
  	<field name="crr_cnt" size="3"/> 
  <struct name="oary" multiplicity="3000">
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="ppbox_id" size="&PPBOX_ID_LEN;"/>
    <field name="crr_stat" size="&CRR_STAT_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="nx_route_cate" size="&CODE_LEN;"/>
    <field name="nx_route_id" size="&ROUTE_ID_LEN;"/>
    <field name="nx_route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="nx_ope_no" size="&OPE_NO_LEN;"/>
    <field name="nx_ope_id" size="&OPE_ID_LEN;"/>
    <field name="nx_ope_dsc" size="&OPE_DSC_LEN;"/>
    <field name="nx_pep_lvl" size="&PEP_LVL_LEN;"/>
    <field name="nx_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="nx_proc_id" size="&PROC_ID_LEN;"/>
    <field name="rsv_user_id" size="&USER_ID_LEN;"/>
    <field name="rsv_eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="rsv_flg" size="&RSV_FLG_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="product_dsc" size="&PRODUCT_DSC_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="prty" size="&CODE_LEN;"/>
    <field name="logof_date" size="&DATE_LEN;"/>
    <field name="logof_time" size="&TIME_LEN;"/>
    <field name="sht_cnt" size="&SHT_STAT_LEN;"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="man_ope_time" size="&LD_TIME_LEN;"/>
    <field name="qrs_avl_flg" size="1"/>
    <field name="qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="qrs_date" size="&DATE_LEN;"/>
    <field name="qrs_time" size="&TIME_LEN;"/>
    <field name="min_qrs_avl_flg" size="1"/>
    <field name="min_qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="min_qrs_date" size="&DATE_LEN;"/>
    <field name="min_qrs_time" size="&TIME_LEN;"/>
    <field name="xf_cmd_stat" size="1"/>
    <field name="position" size="&EQPT_ID_LEN;"/>
    <field name="lot_note_flg" size="1"/>
    <field name="ld_crr_asgn_mode" size="1"/>
    <field name="assign_valid" size="1"/>
    <field name="max_qrk_avl_flg" size="1"/>
    <field name="max_qrk_ope_id" size="&OPE_ID_LEN;"/>
    <field name="max_qrk_date" size="&DATE_LEN;"/>
    <field name="max_qrk_time" size="&TIME_LEN;"/>
    <field name="no_xfer_flg" size="1"/>
    <field name="no_xfer_typ" size="1"/>
    <field name="product_cate" size="&CODE_LEN;"/>
    <field name="owner_id" size="&OWNER_ID_LEN;"/>
    <field name="move_in_flg" size="1"/>
    <field name="worder_id" size="&WORDER_ID_LEN;"/>
    <field name="unit" size="&CODE_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apieqshso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPIEQSHS</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
  	<field name="his_cnt" size="4"/>
  <struct name="oary" multiplicity="1000">
    <field name="clm_date" size="&DATE_LEN;"/>
    <field name="clm_time" size="&TIME_LEN;"/>
    <field name="clm_mfdt" size="&DATE_LEN;"/>
    <field name="clm_mfwk" size="&MFGWEEK_LEN;"/>
    <field name="clm_mfmn" size="&MFGMONTH_LEN;"/>
    <field name="clm_mfsh" size="&MFGSHOP_LEN;"/>
    <field name="report_date" size="&DATE_LEN;"/>
    <field name="report_time" size="&TIME_LEN;"/>
    <field name="report_mfsh" size="&MFGSHOP_LEN;"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_sub_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
    <field name="pv_eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="pv_eqpt_sub_stat" size="&EQPT_STAT_LEN;"/>
    <field name="shtng_date" size="&DATE_LEN;"/>
    <field name="shtng_time" size="&TIME_LEN;"/>
    <field name="shtng_user" size="&USER_ID_LEN;"/>
    <field name="reason_code" size="&CODE_LEN;"/>
    <field name="clm_user" size="&USER_ID_LEN;"/>
    <field name="comment" size="&COMMENT_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/aplhcstco.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % alglen SYSTEM "alglen.dtd"> %alglen;
]>
<struct name="transaction">
  <field name="trx_id" size="&TRX_ID_LEN;"/>
  <field name="type_id" size="&TRX_TYP_LEN;"/>
  <field name="rtn_code" size="&RTN_CODE_LEN;"/>
  <field name="crr_cnt" size="4"/>
  <struct name="oary" multiplicity="3000">
    <field name="pp_maker_code" size="&PP_MAKER_CODE_LEN;"/>
    <field name="pp_hinmei" size="&PP_HINMEI_LEN;"/>
    <field name="pp_mtrl_lot_id" size="&PP_MTRL_LOT_ID_LEN;"/>
    <field name="pp_process" size="1"/>
    <field name="pp_case_id" size="&PP_CASE_ID_LEN;"/>
    <field name="pp_type" size="&PP_TYPE_LEN;"/>
    <field name="pp_type_dsc" size="&CODE_DSC_LEN;"/>
    <field name="xf_cmd_stat" size="1"/>
    <field name="sht_cnt" size="&SHT_CNT_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="hapho_name" size="&HAPHO_NAME_LEN;"/>
    <field name="lst_stc_in_date" size="&DATE_LEN;"/>
    <field name="lst_stc_in_time" size="&TIME_LEN;"/>
    <field name="shelf_id" size="&SHELF_ID_LEN;"/>
    <field name="pp_cyooti" size="&PP_CYOOTI_LEN;"/>
    <field name="pp_cell_aid" size="&PP_CELL_AID_LEN;"/>
    <field name="pp_to_code" size="1"/>
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="position" size="&EQPT_ID_LEN;"/>
    <field name="port_id" size="&PORT_ID_LEN;"/>
    <field name="pati_id" size="&PATI_ID_LEN;"/>
    <field name="zone_id" size="&ZONE_ID_LEN;"/>
    <field name="receipt_no" size="&RECEIPT_NO_LEN;"/>
    <field name="ticket_no" size="&AMHS_TICKET_NO_LEN;"/>
    <field name="xfer_clm_date" size="&DATE_LEN;"/>
    <field name="xfer_clm_time" size="&TIME_LEN;"/>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/aplicrsho.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPLICRSH</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_dsc" size="&EQPT_DSC_LEN;"/>
    <field name="recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
  <field name="crr_cnt" size="4"/>
  <struct name="oary1" multiplicity="3000">
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="crr_stat" size="&CRR_STAT_LEN;"/>
    <field name="ppbox_id" size="&PPBOX_ID_LEN;"/>
    <field name="cr_route_id" size="&ROUTE_ID_LEN;"/>
    <field name="cr_route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="cr_ope_no" size="&OPE_NO_LEN;"/>
    <field name="cr_ope_id" size="&OPE_ID_LEN;"/>
    <field name="cr_ope_ver" size="&OPE_VER_LEN;"/>
    <field name="cr_pep_lvl" size="&PEP_LVL_LEN;"/>
    <field name="cr_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="prty" size="&CODE_LEN;"/>
    <field name="logon_date" size="&DATE_LEN;"/>
    <field name="logon_time" size="&TIME_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="cr_ope_dsc" size="&OPE_DSC_LEN;"/>
    <field name="man_ope_time" size="&LD_TIME_LEN;"/>
    <field name="max_qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="max_qrs_date" size="&DATE_LEN;"/>
    <field name="max_qrs_time" size="&TIME_LEN;"/>
    <field name="max_qrk_date" size="&DATE_LEN;"/>
    <field name="max_qrk_time" size="&TIME_LEN;"/>
    <field name="min_qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="min_qrs_date" size="&DATE_LEN;"/>
    <field name="min_qrs_time" size="&TIME_LEN;"/>
    <field name="min_qrk_date" size="&DATE_LEN;"/>
    <field name="min_qrk_time" size="&TIME_LEN;"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="abnd_flg" size="1"/>
    <field name="proc_id" size="&PROC_ID_LEN;"/>
    <field name="pr_flg" size="1"/>
    <field name="unit" size="&CODE_LEN;"/>
    <field name="mes_id" size="&MES_ID_LEN;"/>
    <field name="sht_cnt" size="&SHT_CNT_LEN;"/>
    <struct name="oary2" multiplicity="&MAX_LOT_SHT_CNT;">
	    <field name="sht_id" size="&SHT_ID_LEN;"/>
	    <field name="sgr_id" size="&SGR_ID_LEN;"/>
	    <field name="lot_id" size="&LOT_ID_LEN;"/>
	    <field name="splt_id" size="&SPLT_ID_LEN;"/>
	    <field name="slot_no" size="&SLOT_NO_LEN;"/>
	    <field name="abnd_flg" size="1"/>
    </struct>
  </struct>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/aplhcstci.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % alglen SYSTEM "alglen.dtd"> %alglen;
]>
<struct name="transaction">
  <field name="trx_id" size="&TRX_ID_LEN;">BPLHCSTC</field>
  <field name="type_id" size="&TRX_TYP_LEN;">I</field>
  <field name="inq_typ" size="1"/>
  <field name="product_id" size="&PRODUCT_ID_LEN;"/>
  <field name="pp_maker_code" size="&PP_MAKER_CODE_LEN;"/>
  <field name="pp_hinmei" size="&PP_HINMEI_LEN;"/>
  <field name="pp_mtrl_lot_id" size="&PP_MTRL_LOT_ID_LEN;"/>
  <field name="pp_process" size="1"/>
  <field name="pp_case_id" size="&PP_CASE_ID_LEN;"/>
  <field name="pp_type" size="&PP_TYPE_LEN;"/>
  <field name="fr_lst_stc_in_date" size="1"/>
  <field name="to_lst_stc_in_date" size="1"/>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apleqalmi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPLEQALM</field>
    <field name="type_id" size="&TRX_TYP_LEN;">I</field>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="cfm_user_id" size="1"/>
    <field name="fr_date" size="&DATE_LEN;"/>
    <field name="fr_time" size="&TIME_LEN;"/>
    <field name="to_date" size="&DATE_LEN;"/>
    <field name="to_time" size="&TIME_LEN;"/>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apiqcrrdo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
  <!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPIQCRRD</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="crr_id" size="&CRR_ID_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="crr_stat" size="&CRR_STAT_LEN;"/>
    <field name="valid_flg" size="1"/>
    <field name="crr_mnt_rst_date" size="&DATE_LEN;"/>
    <field name="sht_cnt" size="&SHT_CNT_LEN;"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="pnl_sht_cnt" size="&PNL_SHT_CNT_LEN;"/>
    <field name="clup_flg" size="1"/>
    <field name="clup_date" size="&DATE_LEN;"/>
    <field name="clup_time" size="&TIME_LEN;"/>
    <field name="real_emp" size="&RELEMP_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="route_cate" size="&CODE_LEN;"/>
    <field name="route_id" size="&ROUTE_ID_LEN;"/>
    <field name="route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="ope_no" size="&OPE_NO_LEN;"/>
    <field name="ope_id" size="&OPE_ID_LEN;"/>
    <field name="ope_ver" size="&OPE_VER_LEN;"/>
    <field name="ope_dsc" size="&OPE_DSC_LEN;"/>
    <field name="stage_id" size="&STAGE_ID_LEN;"/>
    <field name="dept_code" size="&DEPT_CODE_LEN;"/>
    <field name="proc_id" size="&PROC_ID_LEN;"/>
    <field name="proc_dsc" size="&CODE_DSC_LEN;"/>
    <field name="priority" size="&PRIORITY_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_port_id" size="&PORT_ID_LEN;"/>
    <field name="eqpt_dsc" size="&EQPT_DSC_LEN;"/>
    <field name="pv_eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="pep_lvl" size="&PEP_LVL_LEN;"/>
    <field name="recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="pv_ope_no" size="&OPE_NO_LEN;"/>
    <field name="mproc_id" size="&CODE_LEN;"/>
    <field name="mproc_flg" size="1"/>
    <field name="wip_bank_flg" size="1"/>
    <field name="def_wip_bank_id" size="&EQPT_ID_LEN;"/>
    <field name="shp_bank_flg" size="1"/>
    <field name="crrg_id" size="&CRR_ID_LEN;"/>
    <field name="crr_use_cnt" size="&CRR_USE_CNT_LEN;"/>
    <field name="max_crr_use_cnt" size="&CRR_USE_CNT_LEN;"/>
    <field name="max_use_over_flg" size="1"/>
    <field name="crr_rwk_cnt" size="&RWK_CNT_LEN;"/>
    <field name="mes_id" size="&MES_ID_LEN;"/>
    <field name="area_code" size="&CODE_LEN;"/>
    <field name="mix_owner" size="1"/>
    <field name="owner_id" size="&OWNER_ID_LEN;"/>
    <field name="unit" size="&CODE_LEN;"/>
    <field name="product_cate" size="&CODE_LEN;"/>
    <field name="map_flg" size="1"/>
    <field name="crr_own" size="&CRR_OWN_LEN;"/>
    <field name="cross_flg" size="1"/>
    <field name="crr_rgst_own" size="&CRR_OWN_LEN;"/>
  <field name="qrs_ary_cnt" size="1"/>
  <struct name="oary2" multiplicity="4">
    <field name="qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="qrs_typ" size="1"/>
    <field name="qrs_date" size="&DATE_LEN;"/>
    <field name="qrs_time" size="&TIME_LEN;"/>
    <field name="qrk_date" size="&DATE_LEN;"/>
    <field name="qrk_time" size="&TIME_LEN;"/>
  </struct>
  <field name="sht_ary_cnt" size="&LOT_SHT_CNT_LEN;"/>
  <struct name="oary1" multiplicity="&MAX_LOT_SHT_CNT;">
    <field name="sht_id" size="&SHT_ID_LEN;"/>
    <field name="sht_stat" size="&SHT_STAT_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="slot_no" size="&SLOT_NO_LEN;"/>
    <field name="reproc_flg" size="1"/>
    <field name="sht_note_flg" size="1"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="pnl_grade" size="&MAX_SHT_PNL_CNT;"/>
    <field name="rwk_cnt" size="&RWK_CNT_LEN;"/>
    <field name="sht_exist_flg" size="1"/>
    <field name="org_lot_id" size="&LOT_ID_LEN;"/>
    <field name="org_prt_splt_id" size="&SPLT_ID_LEN;"/>
    <field name="org_splt_id" size="&SPLT_ID_LEN;"/>
    <field name="lg_scrp_flg" size="1"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="route_cate" size="&CODE_LEN;"/>
    <field name="route_id" size="&ROUTE_ID_LEN;"/>
    <field name="route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="ope_no" size="&OPE_NO_LEN;"/>
    <field name="ope_id" size="&OPE_ID_LEN;"/>
    <field name="ope_ver" size="&OPE_VER_LEN;"/>
    <field name="mtrl_grade" size="&MTRL_GRADE_LEN;"/>
    <field name="stb_shop" size="&CODE_LEN;"/>
    <field name="mix_owner" size="1"/>
    <field name="owner_id" size="&OWNER_ID_LEN;"/>
    <field name="stage_id" size="&STAGE_ID_LEN;"/>
    <field name="abn_cnt" size="2"/>
    <struct name="oary3" multiplicity="10">
        <field name="seq_no" size="&SEQ_NO_LEN;"/>
    <field name="abnormal_flg" size="&ABNORMAL_FLG_LEN;"/>
    </struct>
  </struct>
</struct>
