=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/lcd-struct.dtd
<!ELEMENT struct (struct|field|array)+>
<!ELEMENT field (#PCDATA)>
<!ELEMENT array (struct|field|array)>
<!ATTLIST struct name CDATA #REQUIRED>
<!ATTLIST struct encoding CDATA #IMPLIED>
<!ATTLIST struct multiplicity CDATA '1'>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field encoding CDATA #IMPLIED>
<!ATTLIST field multiplicity CDATA '1'>
<!ATTLIST field size CDATA '0'>
<!ATTLIST array name CDATA #REQUIRED>
<!ATTLIST array encoding CDATA #IMPLIED>
<!ATTLIST array multiplicity CDATA '1'>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/apinqloto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPINQLOT</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="lot_stat" size="&LOT_STAT_LEN;"/>
    <field name="temp_lot_flg" size="1"/>
    <field name="product_cate" size="&CODE_LEN;"/>
    <field name="ppbox_id" size="&PPBOX_ID_LEN;"/>
    <field name="stb_sht_cnt" size="&SHT_CNT_LEN;"/>
    <field name="pnl_sht_cnt" size="&PNL_SHT_CNT_LEN;"/>
    <field name="lot_note_flg" size="1"/>
    <field name="pln_stb_date" size="&DATE_LEN;"/>
    <field name="pln_cmp_date" size="&DATE_LEN;"/>
    <field name="pln_cmp_time" size="&TIME_LEN;"/>
    <field name="pln_cmp_mfdt" size="&DATE_LEN;"/>
    <field name="pln_cmp_mfwk" size="&MFGWEEK_LEN;"/>
    <field name="pln_cmp_mfmn" size="&MFGMONTH_LEN;"/>
    <field name="pln_cmp_mfsh" size="&MFGSHOP_LEN;"/>
    <field name="act_stb_user" size="&USER_ID_LEN;"/>
    <field name="act_stb_date" size="&DATE_LEN;"/>
    <field name="act_stb_time" size="&TIME_LEN;"/>
    <field name="act_stb_mfdt" size="&DATE_LEN;"/>
    <field name="act_stb_mfwk" size="&MFGWEEK_LEN;"/>
    <field name="act_stb_mfmn" size="&MFGMONTH_LEN;"/>
    <field name="act_stb_mfsh" size="&MFGSHOP_LEN;"/>
    <field name="mtrl_product_id" size="&MTRL_ID_LEN;"/>
    <field name="worder_id" size="&WORDER_ID_LEN;"/>
    <field name="sales_order" size="&SALES_ORDER_LEN;"/>
    <field name="stb_fab_id" size="&FAB_ID_LEN;"/>
    <field name="stb_line_id" size="&LINE_ID_LEN;"/>
    <field name="stb_product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="stb_ec_code" size="&EC_CODE_LEN;"/>
    <field name="stb_route_id" size="&ROUTE_ID_LEN;"/>
    <field name="stb_route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="stb_charge_code" size="&CHARGE_CODE_LEN;"/>
    <field name="stb_owner_id" size="&OWNER_ID_LEN;"/>
    <field name="stb_prty" size="&CODE_LEN;"/>
    <field name="last_splt_id" size="&SPLT_ID_LEN;"/>
    <field name="rel_date" size="&DATE_LEN;"/>
    <field name="crt_aft_stb_flg" size="1"/>
    <field name="chg_stat_date" size="&DATE_LEN;"/>
    <field name="chg_stat_time" size="&TIME_LEN;"/>
    <field name="dest_shop" size="&CODE_LEN;"/>
</struct>

=== yorkiiz/java/cim/wfm/WFM/WFMServer/src/com/ibm/lcd/trx/aplieqsho.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struct SYSTEM "lcd-struct.dtd" [
<!ENTITY % xlglen SYSTEM "xlglen.dtd"> %xlglen;
]>
<struct name="transaction">
    <field name="trx_id" size="&TRX_ID_LEN;">BPLIEQSH</field>
    <field name="type_id" size="&TRX_TYP_LEN;">O</field>
    <field name="rtn_code" size="&RTN_CODE_LEN;"/>
    <field name="rtn_mesg" size="&RTN_MESG_LEN;"/>
    <field name="eqpt_id" size="&EQPT_ID_LEN;"/>
    <field name="eqpt_dsc" size="&EQPT_DSC_LEN;"/>
    <field name="recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="eqpt_stat" size="&EQPT_STAT_LEN;"/>
    <field name="eqpt_stat_dsc" size="&CODE_DSC_LEN;"/>
    <field name="eqpt_mode" size="&EQPT_MODE_LEN;"/>
  <field name="sht_cnt" size="5"/>
  <struct name="oary" multiplicity="10000">
    <field name="sht_id" size="&SHT_ID_LEN;"/>
    <field name="sgr_id" size="&SGR_ID_LEN;"/>
    <field name="lot_id" size="&LOT_ID_LEN;"/>
    <field name="splt_id" size="&SPLT_ID_LEN;"/>
    <field name="logon_crr_id" size="&CRR_ID_LEN;"/>
    <field name="logon_slot_no" size="&SLOT_NO_LEN;"/>
    <field name="cr_route_id" size="&ROUTE_ID_LEN;"/>
    <field name="cr_route_ver" size="&ROUTE_VER_LEN;"/>
    <field name="cr_ope_no" size="&OPE_NO_LEN;"/>
    <field name="cr_ope_id" size="&OPE_ID_LEN;"/>
    <field name="cr_ope_ver" size="&OPE_VER_LEN;"/>
    <field name="cr_pep_lvl" size="&PEP_LVL_LEN;"/>
    <field name="cr_recipe_id" size="&RECIPE_ID_LEN;"/>
    <field name="product_id" size="&PRODUCT_ID_LEN;"/>
    <field name="product_dsc" size="&PRODUCT_DSC_LEN;"/>
    <field name="ec_code" size="&EC_CODE_LEN;"/>
    <field name="prty" size="&CODE_LEN;"/>
    <field name="logon_date" size="&DATE_LEN;"/>
    <field name="logon_time" size="&TIME_LEN;"/>
    <field name="pnl_cnt" size="&PNL_CNT_LEN;"/>
    <field name="cr_ope_dsc" size="&OPE_DSC_LEN;"/>
    <field name="man_ope_time" size="&LD_TIME_LEN;"/>
    <field name="max_qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="max_qrs_date" size="&DATE_LEN;"/>
    <field name="max_qrs_time" size="&TIME_LEN;"/>
    <field name="max_qrk_date" size="&DATE_LEN;"/>
    <field name="max_qrk_time" size="&TIME_LEN;"/>
    <field name="min_qrs_ope_id" size="&OPE_ID_LEN;"/>
    <field name="min_qrs_date" size="&DATE_LEN;"/>
    <field name="min_qrs_time" size="&TIME_LEN;"/>
    <field name="min_qrk_date" size="&DATE_LEN;"/>
    <field name="min_qrk_time" size="&TIME_LEN;"/>
    <field name="abnd_flg" size="1"/>
    <field name="cr_proc_id" size="&PROC_ID_LEN;"/>
    <field name="sht_note_flg" size="1"/>
    <field name="reproc_flg" size="1"/>
    <field name="stage_id" size="&STAGE_ID_LEN;"/>
    <field name="mtrl_product_id" size="&MTRL_ID_LEN;"/>
    <field name="lg_scrp_flg" size="1"/>
    <field name="unit" size="&CODE_LEN;"/>
    <field name="mes_id" size="&MES_ID_LEN;"/>
  </struct>
</struct>
